services:
  n8nio:
    image: docker.n8n.io/n8nio/n8n
    volumes:
      - './volume-data/n8n_data:/home/node/.n8n'
    environment:
      - DB_POSTGRESDB_PASSWORD=<POSTGRES_PASSWORD>
      - DB_POSTGRESDB_SCHEMA=<POSTGRES_SCHEMA>
      - DB_POSTGRESDB_USER=<POSTGRES_USER>
      - DB_POSTGRESDB_PORT=<POSTGRES_PORT>
      - DB_POSTGRESDB_HOST=<POSTGRES_HOST>
      - DB_POSTGRESDB_DATABASE=<POSTGRES_DATABASE>
      - DB_TYPE=postgresdb
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - TZ=America/Chicago
      - GENERIC_TIMEZONE=America/Chicago
    ports:
      - '5678:5678'
    container_name: n8n
    tty: true
    stdin_open: true
