version: "3.7"
services:
  postgres:
    container_name: db-tools-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    container_name: db-tools-adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_PLUGINS: 'dump-json tables-filter json-column sql-log sql-gemini'
  mongo:
    image: mongo
    container_name: db-tools-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: richard
      MONGO_INITDB_ROOT_PASSWORD: password
    command: ["mongod", "--auth"]
    volumes:
      - ./mongodata:/data/db
  mongo-express:
    container_name: db-tools-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://richard:password@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: richard
      ME_CONFIG_BASICAUTH_PASSWORD: password
  redis:
    image: redis:latest
    container_name: db-tools-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  pgdata: {}
  redis_data: {}
  mongodata: {}
networks:
  default: {}