services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_ce_latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume-data/portainer_data:/data
volumes:
  portainer_data: