services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=502
      - PGID=20
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ./volume-data/firefox/config:/config
    ports:
      - 3300:3000
      - 3301:3001
    shm_size: "1gb"
    restart: unless-stopped